{% set name = "gqrx" %}
{% set version = "2.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csete/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ec5cf2eab77e1e42931e5397e664cf167b45241f9e2ddecfef1ebae802bbc9bf
  patches:
    - 0001-Don-t-build-a-resource-file-for-the-executable-on-Wi.patch  # [win]
    - 0002-Don-t-build-a-win32-app-instead-of-a-console-app.patch  # [win]
    - 0001-Increase-random-file-size-so-empty-receive-source-wo.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config  # [not win]
   # libudev needed to link against libusb (through gnuradio-osmosdr) on linux
    - {{ cdt('libudev') }}  # [linux]
   # below are needed to link with Qt for qtgui
    - {{ cdt('libice') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm') }}  # [linux]
    - {{ cdt('libx11') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - gnuradio-core
    - gnuradio-osmosdr
    - pulseaudio  # [linux]
    - qt
    # pulled in by gnuradio-core and linked against, so include explicitly
    - boost-cpp
    - log4cpp
    # 1.3.6 doesn't work well now due to linking issue - conda-forge/libvorbis-feedstock#14
    # otherwise don't need to depend on this explicitly
    - libvorbis <1.3.6
  run:
    # pulled in by gnuradio-core and linked against, so include explicitly
    - boost-cpp
    - log4cpp
    # 1.3.6 doesn't work well now due to linking issue - conda-forge/libvorbis-feedstock#14
    # otherwise don't need to depend on this explicitly
    - libvorbis <1.3.6

test:
  commands:
    # can't test whether it runs because a display is needed
    - test -f $PREFIX/bin/gqrx  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\gqrx.exe exit 1  # [win]

app:
  entry: gqrx --edit
  icon: gqrx-icon.png
  summary: Gqrx
  type: desk

about:
  home: https://gqrx.dk/
  license: GPL-3.0-or-later AND Apache-2.0
  license_family: GPL
  license_file:
    - COPYING
    - LICENSE-CTK
  summary: Software defined radio receiver powered by GNU Radio and Qt
  description: |
    Gqrx is an open source software defined radio (SDR) receiver implemented using GNU
    Radio and the Qt GUI toolkit. Currently it works on Linux and Mac with hardware
    supported by gr-osmosdr, including Funcube Dongle, RTL-SDR, Airspy, HackRF,
    BladeRF, RFSpace, USRP and SoapySDR.

    Gqrx can operate as an AM/FM/SSB receiver with audio output or as an FFT-only
    instrument. There are also various hooks for interacting with external application
    using network sockets.
  dev_url: https://github.com/csete/gqrx

extra:
  recipe-maintainers:
    - ryanvolz
